In [106]:
import pandas as pd
import numpy as np

In [107]:
df=pd.read_excel("Raw_Reviews_WM.xlsx")
df.head()

Unnamed: 0                                         r_title  \
0           0       Got repaired 3 times within 4-6 months :(   
1           1  useless completely not an user friendly device   
2           2                  Very very good but not stable.   
3           3            Voltage hi low errer and ifb service   
4           4                                           Great   

             r_rating                                          r_review   
0  3.0 out of 5 stars  \n\n  Got repaired 3 times in the span of 4 to...  
1  1.0 out of 5 stars  \n\n  Not an user friendly device requires com...  
2  5.0 out of 5 stars  \n\n  The machine is very good no doubt.Washin...  
3  1.0 out of 5 stars  \n\n  Before it I am using LG washing machine ...  
4  5.0 out of 5 stars                     \n\n  Nice value for money\n\n

In [108]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [109]:
df["rating"]= df["r_rating"].apply(lambda x : int(x[0]))
df.drop("r_rating", axis=1, inplace=True)
df.head()

r_title  \
0       Got repaired 3 times within 4-6 months :(   
1  useless completely not an user friendly device   
2                  Very very good but not stable.   
3            Voltage hi low errer and ifb service   
4                                           Great   

                                           r_review   rating  
0  \n\n  Got repaired 3 times in the span of 4 to...       3  
1  \n\n  Not an user friendly device requires com...       1  
2  \n\n  The machine is very good no doubt.Washin...       5  
3  \n\n  Before it I am using LG washing machine ...       1  
4                     \n\n  Nice value for money\n\n       5

In [110]:
df_title = df[["r_title","rating"]]
df_title.columns=["Review", "rating"]
df_title.head()

Review  rating
0       Got repaired 3 times within 4-6 months :(       3
1  useless completely not an user friendly device       1
2                  Very very good but not stable.       5
3            Voltage hi low errer and ifb service       1
4                                           Great       5

In [111]:
df_rev = df[["r_review ","rating"]]
df_rev.columns=["Review", "rating"]
df_rev.head()

Review  rating
0  \n\n  Got repaired 3 times in the span of 4 to...       3
1  \n\n  Not an user friendly device requires com...       1
2  \n\n  The machine is very good no doubt.Washin...       5
3  \n\n  Before it I am using LG washing machine ...       1
4                     \n\n  Nice value for money\n\n       5

In [112]:
df1= pd.concat([df_title, df_rev], axis=0).reset_index(drop=True)
df1.head()

Review  rating
0       Got repaired 3 times within 4-6 months :(       3
1  useless completely not an user friendly device       1
2                  Very very good but not stable.       5
3            Voltage hi low errer and ifb service       1
4                                           Great       5

In [113]:
df1.isnull().sum()

Review    5
rating    0
dtype: int64

In [114]:
df1.dropna(inplace=True)

In [115]:
df1.reset_index(drop=True).head()

Review  rating
0       Got repaired 3 times within 4-6 months :(       3
1  useless completely not an user friendly device       1
2                  Very very good but not stable.       5
3            Voltage hi low errer and ifb service       1
4                                           Great       5

In [116]:
import warnings
warnings.filterwarnings(action="ignore")

In [117]:
# Lets Consider rating of 1 ,2 and 3 as Negative review , and considering Negative review as 0
# Lets Consider rating of 4, 5 as Positive Review , and conidering Positive review as 1

df1["sentiment"]= df1["rating"].map({1: 0, 2:0, 3:0, 4: 1, 5:1})
df1.head()

Review  rating  sentiment
0       Got repaired 3 times within 4-6 months :(       3          0
1  useless completely not an user friendly device       1          0
2                  Very very good but not stable.       5          1
3            Voltage hi low errer and ifb service       1          0
4                                           Great       5          1

In [118]:
df1.sentiment.value_counts()

1    1352
0     743
Name: sentiment, dtype: int64

In [119]:
import re
from nltk.stem import PorterStemmer , WordNetLemmatizer
from nltk import word_tokenize
from nltk.corpus import stopwords

In [120]:
lemmatizer=WordNetLemmatizer()

In [121]:
def text_cleaner (text):
    cleaned= re.sub('[^a-zA-Z]', " ", text) 
    cleaned= cleaned.lower()
    cleaned = cleaned.split()
    cleaned= [lemmatizer.lemmatize (word) for word in cleaned]
    cleaned= ' '.join(cleaned)
    return cleaned

In [122]:
df_final= df1[["Review", "sentiment"]]
df_final

Review  sentiment
0             Got repaired 3 times within 4-6 months :(          0
1        useless completely not an user friendly device          0
2                        Very very good but not stable.          1
3                  Voltage hi low errer and ifb service          0
4                                                 Great          1
...                                                 ...        ...
2095  \n\n  What a budget product from IFB. Works ve...          1
2096  \n\n  Please please please don't buy ifb even ...          0
2097  \n\n  Washing machine gets stuck if you put mo...          0
2098  \n\n  Pathetic after sales service by IFB. Wil...          0
2099  \n\n  Waste product delicate duplicate colityD...          0

[2095 rows x 2 columns]

In [123]:
df_final["Cleaned"] = df_final["Review"].apply(lambda x : text_cleaner(x))
df_final

Review  sentiment  \
0             Got repaired 3 times within 4-6 months :(          0   
1        useless completely not an user friendly device          0   
2                        Very very good but not stable.          1   
3                  Voltage hi low errer and ifb service          0   
4                                                 Great          1   
...                                                 ...        ...   
2095  \n\n  What a budget product from IFB. Works ve...          1   
2096  \n\n  Please please please don't buy ifb even ...          0   
2097  \n\n  Washing machine gets stuck if you put mo...          0   
2098  \n\n  Pathetic after sales service by IFB. Wil...          0   
2099  \n\n  Waste product delicate duplicate colityD...          0   

                                                Cleaned  
0                        got repaired time within month  
1        useless completely not an user friendly device  
2                         very very good but not stable  
3                  voltage hi low errer and ifb service  
4                                                 great  
...                                                 ...  
2095  what a budget product from ifb work very well ...  
2096  please please please don t buy ifb even if it ...  
2097  washing machine get stuck if you put more than...  
2098  pathetic after sale service by ifb will never ...  
2099  waste product delicate duplicate colitydoors a...  

[2095 rows x 3 columns]

In [124]:
df_final.drop("Review", axis=1, inplace=True)
df_final

sentiment                                            Cleaned
0             0                     got repaired time within month
1             0     useless completely not an user friendly device
2             1                      very very good but not stable
3             0               voltage hi low errer and ifb service
4             1                                              great
...         ...                                                ...
2095          1  what a budget product from ifb work very well ...
2096          0  please please please don t buy ifb even if it ...
2097          0  washing machine get stuck if you put more than...
2098          0  pathetic after sale service by ifb will never ...
2099          0  waste product delicate duplicate colitydoors a...

[2095 rows x 2 columns]

In [125]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence  import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.text import one_hot 
from tensorflow.keras.layers import Dropout 

In [126]:
voc_size= 10000

In [127]:
X= df_final["Cleaned"]

In [128]:
y= df_final["sentiment"]

In [129]:
import tensorflow as tf
tf.__version__

'2.8.0'

In [130]:
x = list(X)
x

['got repaired time within month',
 'useless completely not an user friendly device',
 'very very good but not stable',
 'voltage hi low errer and ifb service',
 'great',
 'very worst service experience by ifb installation guy',
 'damage product',
 'no box content paper no proper inlet pipe',
 'bad bad experience',
 'dont buy this',
 'amazon should ban this from selling online a it is the worst front load washing',
 'worst washing machine',
 'value for money',
 'relatively lesser warranty but received better feedback',
 'don t go for it through amazon',
 'excellent',
 'pathetic performance',
 'best bet recommended',
 'good product',
 'defective machine no redressal either from ifb or amazon',
 'worst service by ifb',
 'rd prime member since disgusted',
 'dissatisfide',
 'great product technology at it best',
 'false commitment',
 'drain pipe length is very le',
 'missing part not yet fixed',
 'worst possible service from ifb',
 'problem',
 'brand new machine not working',
 'worst insta

In [131]:
onehot = [one_hot(words, voc_size) for words in x]
onehot

[[1873, 8630, 410, 6785, 9342],
 [7216, 913, 6011, 490, 2004, 255, 2282],
 [5775, 5775, 4806, 4692, 6011, 3072],
 [4590, 5715, 1175, 9646, 9834, 5135, 8800],
 [5608],
 [5775, 4914, 8800, 765, 1919, 5135, 550, 8867],
 [2313, 3622],
 [1404, 8154, 3314, 6326, 1404, 8011, 6402, 2498],
 [4755, 4755, 765],
 [5248, 7712, 5567],
 [6720,
  8334,
  3904,
  5567,
  377,
  5682,
  9631,
  5093,
  8633,
  8592,
  9492,
  4914,
  6088,
  2480,
  3382],
 [4914, 3382, 5145],
 [8997, 5704, 7188],
 [5306, 3189, 7591, 4692, 8696, 7366, 8086],
 [9720, 5687, 1761, 5704, 8633, 375, 6720],
 [8863],
 [471, 5686],
 [9016, 3080, 4801],
 [4806, 3622],
 [8724, 5145, 1404, 9050, 5548, 377, 5135, 842, 6720],
 [4914, 8800, 1919, 5135],
 [5660, 7461, 9922, 9186, 1734],
 [6493],
 [5608, 3622, 7727, 8218, 8633, 9016],
 [5742, 6950],
 [3509, 2498, 9066, 8592, 5775, 1752],
 [244, 5177, 6011, 2114, 1799],
 [4914, 7087, 8800, 377, 5135],
 [6226],
 [6820, 9612, 5145, 6011, 1124],
 [4914, 550, 3308, 8800],
 [5135, 4023, 9492

In [132]:
sent_length = 20
embedded = pad_sequences(onehot, maxlen=sent_length, padding='pre' )
embedded

array([[   0,    0,    0, ...,  410, 6785, 9342],
       [   0,    0,    0, ..., 2004,  255, 2282],
       [   0,    0,    0, ..., 4692, 6011, 3072],
       ...,
       [   0,    0,    0, ..., 6133,  870, 2169],
       [   0,    0,    0, ..., 5135, 3622, 6447],
       [   0, 7740, 3622, ..., 6011, 9504, 3460]])

In [133]:
emmbedding_vectors= 40
model = Sequential()
model.add(Embedding(voc_size,20, input_length= sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1, activation= "sigmoid"))
model.compile(loss= "binary_crossentropy", optimizer = "adam", metrics= ["accuracy"])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 20, 20)            200000    
                                                                 
 dropout_6 (Dropout)         (None, 20, 20)            0         
                                                                 
 lstm_3 (LSTM)               (None, 100)               48400     
                                                                 
 dropout_7 (Dropout)         (None, 100)               0         
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 248,501
Trainable params: 248,501
Non-trainable params: 0
_________________________________________________________________
None


In [134]:
x_final =np.array(embedded)
y_final = np.array(y)
x_final.shape, y_final.shape

((2095, 20), (2095,))

In [135]:
from sklearn.model_selection import train_test_split

In [136]:
X_train, X_test, y_train, y_test = train_test_split( x_final, y_final, test_size=0.33, random_state=42)

In [137]:
model.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=5, batch_size = 40)

Epoch 1/5
36/36 [==============================] - 5s 50ms/step - loss: 0.6412 - accuracy: 0.6386 - val_loss: 0.5956 - val_accuracy: 0.6980
Epoch 2/5
36/36 [==============================] - 1s 32ms/step - loss: 0.5734 - accuracy: 0.7149 - val_loss: 0.5497 - val_accuracy: 0.7384
Epoch 3/5
36/36 [==============================] - 1s 32ms/step - loss: 0.5129 - accuracy: 0.7655 - val_loss: 0.5027 - val_accuracy: 0.7645
Epoch 4/5
36/36 [==============================] - 1s 32ms/step - loss: 0.4034 - accuracy: 0.8125 - val_loss: 0.4384 - val_accuracy: 0.8035
Epoch 5/5
36/36 [==============================] - 1s 34ms/step - loss: 0.3164 - accuracy: 0.8731 - val_loss: 0.4217 - val_accuracy: 0.8454


In [149]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")

In [150]:
from sklearn.metrics import confusion_matrix, classification_report

In [151]:
print(confusion_matrix(y_test, y_pred))

[[184  49]
 [ 58 401]]


In [152]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      0.79      0.77       233
           1       0.89      0.87      0.88       459

    accuracy                           0.85       692
   macro avg       0.83      0.83      0.83       692
weighted avg       0.85      0.85      0.85       692



In [171]:
txt = "return the the product"

In [172]:
cor = text_cleaner(txt)

In [173]:
onehot = [one_hot(cor, voc_size) ]
onehot 

[[291, 9492, 9492, 3622]]

In [174]:
embedded = pad_sequences(onehot, maxlen=sent_length, padding='pre' )
embedded = np.array(embedded)

In [175]:
embedded 

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,  291, 9492, 9492, 3622]])

In [176]:
(model.predict(embedded)>0.5).astype("int32")

array([[0]])